import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
 
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="p-6 bg-gray-900">     
      <body className={inter.className}>
        <nav className="text-white rounded-sm">
          <ul className="flex float-right">
            <li>
              <Link href="/"> Home </Link>
            </li>
            <li>
              <Link href="/about"> About </Link>
            </li>
          </ul>  
        </nav>
        <hr></hr>
        {children}
      </body>
    </html>
  );
}
